# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dt-solacc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dt-solacc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64t-solacc.proto\"\xc4\x02\n\x0b\x44igitalTwin\x12\x17\n\x0foil_temperature\x18\x01 \x01(\x01\x12\x19\n\x11water_temperature\x18\x02 \x01(\x01\x12\x12\n\nbelt_speed\x18\x03 \x01(\x01\x12\x1b\n\x13\x66reezer_temperature\x18\x04 \x01(\x01\x12\x18\n\x10moisture_content\x18\x05 \x01(\x01\x12\x16\n\x0eproduct_weight\x18\x06 \x01(\x01\x12\x1e\n\x16\x63omponent_yield_output\x18\x07 \x01(\x01\x12\x11\n\ttimestamp\x18\x08 \x01(\t\x12\x14\n\x0c\x63omponent_id\x18\t \x01(\t\x12\x10\n\x08stage_id\x18\n \x01(\t\x12\x19\n\x11\x64\x61maged_component\x18\x0b \x01(\x08\x12\x17\n\x0f\x61\x62normal_sensor\x18\x0c \x01(\t\x12\x0f\n\x07line_id\x18\r \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dt_solacc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIGITALTWIN']._serialized_start=20
  _globals['_DIGITALTWIN']._serialized_end=344
# @@protoc_insertion_point(module_scope)
