command:
- python
- server.py
env:
- name: WAREHOUSE_ID
  valueFrom: sql_warehouse
- name: SYNCED_TABLE_FULL_NAME
  value: simplot-potato-lakebase.frozen_potato.latest_sensor_triples
- name: TRIPLE_TABLE_FULL_NAME
  value: ankit_yadav.frozen_potato.triples
- name: DATABRICKS_CATALOG
  value: ankit_yadav
- name: DATABRICKS_SCHEMA
  value: frozen_potato
- name: DATABRICKS_TABLE
  value: potato_sensor_bronze
- name: LAKEBASE_INSTANCE_NAME
  value: simplot-potato-lakebase
- name: PG_TOKEN_REFRESH_SECONDS
  value: '900'
- name: RDF_MODELS_FULL_TABLE_NAME
  value: digitaltwin.rdf_models
- name: PGDATABASE
  value: simplot-potato-lakebase
